# Generated by Django 6.0.6 on 2026-06-29 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=5)),
                ('Height', models.CharField()),
                ('Weight', models.CharField()),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Age', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('Phone_number', models.CharField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=80, null=True)),
                ('User_Name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_address', models.CharField(blank=True, null=True)),
                ('Office_Address', models.CharField(blank=True, null=True)),
                ('House_Phone', models.CharField(blank=True, null=True)),
                ('Emai_Password', models.CharField(blank=True, null=True)),
                ('Phone_password', models.CharField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part_one.person')),
            ],
        ),
    ]
