# Generated by Django 6.0.6 on 2026-06-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
