# Generated by Django 6.0.6 on 2026-06-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_one', '0002_alter_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_data',
            name='photo_of_person',
            field=models.ImageField(blank=True, null=True, upload_to='C:/Users/Axis.market/Desktop/projects/test_jango/way_of_the_django/photos'),
        ),
    ]
