# Generated by Django 6.0.6 on 2026-06-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_one', '0003_personal_data_photo_of_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_data',
            name='photo_of_person',
            field=models.ImageField(blank=True, null=True, upload_to='upload/photos'),
        ),
    ]
