# Generated by Django 6.0.6 on 2026-07-01 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_one', '0004_alter_personal_data_photo_of_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_data',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='part_one.person'),
        ),
    ]
