# Generated by Django 6.0.6 on 2026-07-07 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_one', '0005_alter_personal_data_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('m', 'male'), ('f', 'female')])),
                ('Height', models.CharField()),
                ('Weight', models.CharField()),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Head_gift', models.CharField()),
                ('role_of_the_character', models.CharField(choices=[('f', 'friendly'), ('unf', 'unfriendly')])),
                ('character_level', models.CharField(choices=[('A', 'AdMiArl'), ('s_a', 'second_AdMiRal'), ('n_m', 'normal_marian')])),
            ],
        ),
        migrations.RenameField(
            model_name='personal_data',
            old_name='photo_of_person',
            new_name='photo_of_the_character',
        ),
        migrations.RemoveField(
            model_name='personal_data',
            name='Emai_Password',
        ),
        migrations.RemoveField(
            model_name='personal_data',
            name='House_Phone',
        ),
        migrations.RemoveField(
            model_name='personal_data',
            name='Phone_password',
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='part_one.character'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
