# Generated by Django 6.0.6 on 2026-07-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part_one', '0006_character_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='character_level',
        ),
    ]
