# Generated by Django 6.0.6 on 2026-07-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_one', '0007_remove_character_character_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_level',
            field=models.CharField(choices=[('y', 'YOnko'), ('SH', 'ShiJeBoKay'), ('n_p', 'normal_pirecy'), ('A', 'AdMiArl'), ('s_a', 'second_AdMiRal'), ('n_m', 'normal_marian')], default=('n_m', 'normal_marian')),
        ),
    ]
