# Generated by Django 6.0.6 on 2026-07-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part_one', '0008_character_character_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_data',
            old_name='person',
            new_name='character',
        ),
    ]
