# Generated by Django 6.0.6 on 2026-07-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_one', '0009_rename_person_personal_data_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_level',
            field=models.CharField(choices=[('y', 'YOnko'), ('SH', 'ShiJeBoKay'), ('n_p', 'normal_pirate'), ('A', 'AdMiArl'), ('s_a', 'second_AdMiRal'), ('n_m', 'normal_marian')], default=('n_m', 'normal_marian')),
        ),
    ]
