# Generated by Django 6.0.6 on 2026-07-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_one', '0010_alter_character_character_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='simple_duc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
