# Generated by Django 6.0.6 on 2026-07-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_one', '0011_character_simple_duc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='Last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
