# Generated by Django 6.0.6 on 2026-07-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_one', '0012_alter_character_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='full_body_photo',
            field=models.ImageField(blank=True, null=True, upload_to='upload/full_body_photos'),
        ),
    ]
