# Generated by Django 6.0.6 on 2026-07-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_one', '0013_character_full_body_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='Gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')]),
        ),
    ]
